#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_static_questions.py — render the question bank into crawler-visible HTML.

WHY THIS EXISTS
---------------
Every topic page used to be an empty <div id="quiz-root"></div> that quiz.js
filled in at runtime. A search-engine crawler (and an AdSense reviewer's
fetcher) sees the raw HTML, so those pages measured 158-186 words each while
the actual product -- 160 explained exam questions -- lived only in bank.js.
Our sister site redsealquiz.ca was rejected twice for "Low value content" for
exactly this reason, and the fix that got it past review was publishing the
questions as static HTML. This script is that fix for part107quiz.com.

WHAT IT DOES
------------
For each topic page it regenerates the block between
  <!-- STATIC-QA:START --> ... <!-- STATIC-QA:END -->
(inserting it just before </main> the first time) containing every question in
that topic: stem, all four options with the correct one marked, the plain
English explanation, and the CFR / FAA reference.

It also rewrites the per-topic question counts that appear in <title>, the meta
description, the on-page intro and index.html, so the advertised number always
matches the bank. Those had drifted (regulations said 31, bank held 41).

The interactive quiz is untouched: it still shuffles options at runtime, so the
static answer key does not spoil the drill above it.

Run after any bank.js edit:  py -3.12 tools/build_static_questions.py
Then:                        py -3.12 tools/qc_bank.py
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

START = "<!-- STATIC-QA:START (generated by tools/build_static_questions.py - do not hand-edit) -->"
END = "<!-- STATIC-QA:END -->"

# topic key -> (page file, human label, heading noun used in the archive intro)
TOPICS = {
    "regulations": ("regulations.html", "Regulations", "regulations"),
    "airspace": ("airspace.html", "Airspace", "airspace"),
    "weather": ("weather.html", "Weather", "weather"),
    "loading-performance": ("loading-performance.html", "Loading &amp; Performance", "loading and performance"),
    "operations": ("operations.html", "Operations", "operations"),
    "night-operations": ("night-operations.html", "Night Operations", "night operations"),
    "remote-id": ("remote-id.html", "Remote ID", "Remote ID"),
}

LETTERS = ["A", "B", "C", "D", "E", "F"]


def esc(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace('"', "&quot;"))


def load_bank():
    src = open(os.path.join(ROOT, "bank.js"), encoding="utf-8").read()
    arr = src[src.index("["):src.rindex("]") + 1]
    return json.loads(arr)


def render_archive(topic, label, noun, items):
    n = len(items)
    out = [START]
    out.append('<section class="qa-archive" id="all-questions">')
    out.append('  <div class="container narrow">')
    out.append('    <h2>All %d %s questions, with answers and references</h2>' % (n, noun))
    out.append(
        '    <p class="qa-lede">The drill above shuffles the answer choices on every attempt. '
        'Below is the same %d-question set written out in full, in a fixed order, so you can read '
        'it straight through, print it, or check a single rule without restarting a quiz. Each '
        'answer carries the reasoning and the FAA source it rests on.</p>' % n)
    out.append('    <ol class="qa-list">')
    for q in items:
        out.append('      <li class="qa" id="q-%s">' % esc(q["id"]))
        out.append('        <p class="qa-q">%s</p>' % esc(q["q"]))
        out.append('        <ul class="qa-opts">')
        for i, opt in enumerate(q["options"]):
            correct = (i == q["answer"])
            cls = ' class="is-correct"' if correct else ""
            tag = ' <span class="qa-tag">Correct answer</span>' if correct else ""
            out.append('          <li%s><span class="qa-l">%s.</span> %s%s</li>'
                       % (cls, LETTERS[i], esc(opt), tag))
        out.append('        </ul>')
        out.append('        <p class="qa-exp"><strong>Why:</strong> %s</p>' % esc(q["exp"]))
        out.append('        <p class="qa-ref">Reference: %s</p>' % esc(q["ref"]))
        out.append('      </li>')
    out.append('    </ol>')
    out.append('    <p class="qa-foot">Ready for the real format? Take the '
               '<a href="./mock-exam.html">full 60-question timed mock exam</a>, which draws from '
               'all seven topics using the FAA\'s published area weighting.</p>')
    out.append('  </div>')
    out.append('</section>')
    out.append(END)
    return "\n".join(out)


def splice(html, block):
    if START in html and END in html:
        return re.sub(re.escape(START) + r".*?" + re.escape(END), lambda m: block,
                      html, flags=re.S)
    if "</main>" not in html:
        raise SystemExit("no </main> anchor")
    return html.replace("</main>", block + "\n</main>", 1)


def add_jump_link(html, n):
    """Put a 'skip to the written set' link under the intro paragraph."""
    marker = '<div id="quiz-root"></div>'
    link = ('<p class="qa-jump"><a href="#all-questions">Prefer to read? '
            'Jump to all %d questions with answers &darr;</a></p>\n  ' % n)
    if "qa-jump" in html:
        html = re.sub(r'<p class="qa-jump">.*?</p>\n\s*', "", html, flags=re.S)
    return html.replace(marker, link + marker, 1)


def retarget_counts(html, topic, n):
    """Rewrite stale question counts in title / description / intro copy."""
    # "<N> Free Questions", "<N> questions", "<N>-question", "Start <N> questions"
    html = re.sub(r'(\d+)(\s+Free\s+(?:Sectional Chart |METAR &amp; TAF |ADM &amp; CRM )?Questions)',
                  lambda m: str(n) + m.group(2), html)
    html = re.sub(r'(?<![\d,])(\d+)(\s*(?:-|\s)question(?:s)?\b)',
                  lambda m: (m.group(0) if m.group(1) in ("60", "50", "160", "300")
                             else str(n) + m.group(2)), html)
    html = re.sub(r'\b(\d+) questions on ', lambda m: "%d questions on " % n, html)
    html = re.sub(r'\b(\d+)( exam-style questions)', lambda m: str(n) + m.group(2), html)
    return html


def main():
    bank = load_bank()
    by_topic = {}
    for q in bank:
        by_topic.setdefault(q["topic"], []).append(q)

    unknown = set(by_topic) - set(TOPICS)
    if unknown:
        raise SystemExit("bank has topics with no page: %s" % sorted(unknown))

    counts = {}
    for topic, (fname, label, noun) in TOPICS.items():
        items = by_topic.get(topic, [])
        if not items:
            raise SystemExit("no questions for topic %s" % topic)
        counts[topic] = len(items)
        path = os.path.join(ROOT, fname)
        html = open(path, encoding="utf-8").read()
        html = splice(html, render_archive(topic, label, noun, items))
        html = add_jump_link(html, len(items))
        html = retarget_counts(html, topic, len(items))
        open(path, "w", encoding="utf-8", newline="\n").write(html)
        print("%-22s %3d questions -> %s" % (topic, len(items), fname))

    # index.html card buttons: "Start NN questions"
    ipath = os.path.join(ROOT, "index.html")
    ihtml = open(ipath, encoding="utf-8").read()
    for topic, (fname, label, noun) in TOPICS.items():
        n = counts[topic]
        ihtml = re.sub(r'(href="\./%s">Start )\d+( questions)' % re.escape(fname),
                       lambda m: m.group(1) + str(n) + m.group(2), ihtml)
    total = len(bank)
    ihtml = re.sub(r'\b\d+\+ (questions|exam-style questions)',
                   lambda m: "%d+ %s" % (total, m.group(1)), ihtml)
    open(ipath, "w", encoding="utf-8", newline="\n").write(ihtml)
    print("index.html   total %d, per-topic counts synced" % total)
    return 0


if __name__ == "__main__":
    sys.exit(main())
